### ISSUE TITLE
Convert install script from shell script to yaml file

### ISSUE THREAD

**Issue by anoriqq** [anoriqq/qpm#12]
like

```yml

install:
  dependencies: [go, git]
  run:
    - git clone github.com/org/repo ~/.repo
    - go install github.com/org/repo@latest

uninstall:
  dependencies: [rm]
  run:
    - rm -rf ~/.repo
    - rm -rf $GOPATH/bin/repo
```
